name: system_network_proxy_platform_interface
description: It's a simple utility of system network proxy which can get and set status of proxy, details of proxy.
version: 1.0.2
homepage: https://github.com/liudonghua123/system_network_proxy
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  pedantic: ^1.8.0
